# Generated by Django 5.2.17 on 2026-08-05 02:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='quote_id',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='quote_id muss dem Muster buch-abschnitt (5-23) oder e-kapitel (e-53) entsprechen', regex='^(\\d{1,2}-\\d{1,3}|e-\\d{1,2})$')]),
        ),
    ]
